import os

EVENT_THRESHOLD_MODEL = int(os.getenv("RETRAIN_EVENT_THRESHOLD_MODEL", "500"))
EVENT_THRESHOLD_CLUSTERS = int(os.getenv("RETRAIN_EVENT_THRESHOLD_CLUSTERS", "200"))
MAX_INTERVAL_MODEL = int(os.getenv("RETRAIN_MAX_INTERVAL_MODEL", str(24 * 60 * 60)))
MAX_INTERVAL_CLUSTERS = int(os.getenv("RETRAIN_MAX_INTERVAL_CLUSTERS", str(6 * 60 * 60)))
